import type { Employee, SessionUser } from "@/types/jtg-one";

export const mockSession: SessionUser = {
  id: "emp-001",
  name: "Aarav Mehta",
  role: "employee",
};

const baseVisibility = {
  pastProjects: true,
  achievements: true,
  strengths: true,
  timeline: true,
  certifications: true,
  domainExperience: true,
  feedbackSummary: false,
  weaknesses: false,
  detailedFeedback: false,
  aiGoals: false,
  managerNotes: false,
  improvementAreas: false,
};

export const employees: Employee[] = [
  {
    id: "emp-001",
    name: "Aarav Mehta",
    email: "aarav.mehta@jtg.example",
    role: "employee",
    designation: "Software Engineer",
    targetDesignation: "Senior Software Engineer",
    currentProject: "Claims Modernization",
    location: "Bengaluru",
    avatarInitials: "AM",
    skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL"],
    domainExperience: ["Insurance", "Claims", "Internal Platforms"],
    achievements: [
      "Reduced claims dashboard load time by 38%",
      "Created onboarding notes for three new engineers",
      "Owned migration of shared form components to TypeScript",
    ],
    strengths: ["Ownership", "Frontend architecture", "Cross-team communication"],
    weaknesses: ["Deep cloud infrastructure exposure", "Advanced system design"],
    improvementAreas: ["Mentor juniors more consistently", "Document API decisions earlier"],
    managerNotes: [
      "Ready for larger module ownership if paired with a senior reviewer for design reviews.",
      "Should get more exposure to planning conversations with product and QA.",
    ],
    certifications: ["AWS Cloud Practitioner", "React Advanced Patterns Workshop"],
    projects: [
      {
        id: "proj-001",
        name: "Claims Modernization",
        role: "Frontend Engineer",
        domain: "Insurance",
        duration: "Jan 2025 - Present",
        impact: "Built reusable claim intake flows and analytics widgets.",
        techStack: ["Next.js", "TypeScript", "React Query", "Recharts"],
        rampUp: {
          status: "completed",
          weeks: 4,
          notes: "Ramp-up improved after access checklist and KT recordings were consolidated.",
        },
      },
      {
        id: "proj-002",
        name: "Agent Portal",
        role: "Full-stack Developer",
        domain: "Insurance",
        duration: "Mar 2024 - Dec 2024",
        impact: "Delivered policy search and quote comparison workflows.",
        techStack: ["React", "Express", "PostgreSQL"],
        rampUp: {
          status: "completed",
          weeks: 6,
          notes: "Initial delay caused by VPN and repository access approvals.",
        },
      },
    ],
    timeline: [
      {
        id: "tl-001",
        date: "2024-03-04",
        type: "induction",
        title: "Joined JTG induction",
        description: "Completed engineering onboarding, security training, and platform overview.",
      },
      {
        id: "tl-002",
        date: "2024-03-18",
        type: "project",
        title: "Assigned to Agent Portal",
        description: "Started as full-stack developer for policy search workflows.",
      },
      {
        id: "tl-003",
        date: "2024-05-03",
        type: "ramp-up",
        title: "Ramp-up completed",
        description: "Closed initial access gaps and shipped first independent feature.",
      },
      {
        id: "tl-004",
        date: "2025-01-13",
        type: "project",
        title: "Moved to Claims Modernization",
        description: "Transitioned to frontend ownership for claim intake experience.",
      },
      {
        id: "tl-005",
        date: "2026-04-18",
        type: "feedback",
        title: "Quarterly feedback imported",
        description: "Latest feedback highlighted ownership and frontend architecture strengths.",
      },
    ],
    visibility: baseVisibility,
    feedbackAnalyses: [
      {
        id: "fb-2026-q2",
        title: "Q2 2026 Feedback Cycle",
        importedAt: "2026-04-18",
        status: "latest",
        overallScore: 84,
        sentiment: "positive",
        summary:
          "Strong execution and ownership. The next growth step is broader design participation and mentoring.",
        categories: [
          { name: "Technical", score: 86, previous: 80, benchmark: 78 },
          { name: "Ownership", score: 91, previous: 84, benchmark: 80 },
          { name: "Communication", score: 82, previous: 76, benchmark: 77 },
          { name: "Collaboration", score: 85, previous: 83, benchmark: 79 },
          { name: "Planning", score: 76, previous: 72, benchmark: 75 },
        ],
        trends: [
          { cycle: "Q2 25", technical: 72, ownership: 74, communication: 69, collaboration: 76 },
          { cycle: "Q3 25", technical: 76, ownership: 80, communication: 72, collaboration: 79 },
          { cycle: "Q4 25", technical: 80, ownership: 84, communication: 76, collaboration: 83 },
          { cycle: "Q2 26", technical: 86, ownership: 91, communication: 82, collaboration: 85 },
        ],
        strengths: ["Takes end-to-end ownership", "Keeps UI quality high", "Communicates blockers early"],
        improvements: ["Increase system design depth", "Delegate and mentor more", "Add more written design notes"],
      },
      {
        id: "fb-2025-q4",
        title: "Q4 2025 Feedback Cycle",
        importedAt: "2025-12-12",
        status: "archived",
        overallScore: 79,
        sentiment: "positive",
        summary: "Reliable delivery with clear progress in ownership and collaboration.",
        categories: [
          { name: "Technical", score: 80, previous: 76, benchmark: 76 },
          { name: "Ownership", score: 84, previous: 80, benchmark: 78 },
          { name: "Communication", score: 76, previous: 72, benchmark: 75 },
          { name: "Collaboration", score: 83, previous: 79, benchmark: 78 },
          { name: "Planning", score: 72, previous: 70, benchmark: 74 },
        ],
        trends: [
          { cycle: "Q2 25", technical: 72, ownership: 74, communication: 69, collaboration: 76 },
          { cycle: "Q3 25", technical: 76, ownership: 80, communication: 72, collaboration: 79 },
          { cycle: "Q4 25", technical: 80, ownership: 84, communication: 76, collaboration: 83 },
        ],
        strengths: ["Dependable delivery", "Good collaboration"],
        improvements: ["Earlier technical design documentation"],
      },
    ],
    goalSuggestions: [
      {
        id: "goal-001",
        title: "Lead a medium-complexity module design",
        priority: "high",
        description: "Own the design proposal, API contract, risks, and rollout plan for one module.",
        timeframe: "Next 8 weeks",
        evidence: "Feedback shows high ownership but planning score trails technical execution.",
      },
      {
        id: "goal-002",
        title: "Mentor one engineer through a feature delivery",
        priority: "medium",
        description: "Pair on planning, review checkpoints, and release notes to build senior readiness.",
        timeframe: "This quarter",
        evidence: "Manager notes suggest readiness for broader team influence.",
      },
      {
        id: "goal-003",
        title: "Build cloud deployment fluency",
        priority: "medium",
        description: "Shadow one release and document the deployment, rollback, and monitoring steps.",
        timeframe: "Next 6 weeks",
        evidence: "Weaknesses include limited deep cloud infrastructure exposure.",
      },
    ],
  },
  {
    id: "emp-002",
    name: "Nisha Rao",
    email: "nisha.rao@jtg.example",
    role: "manager",
    designation: "Engineering Manager",
    targetDesignation: "Senior Engineering Manager",
    currentProject: "Platform Enablement",
    location: "Pune",
    avatarInitials: "NR",
    skills: ["People Management", "Delivery", "React", "Node.js", "Architecture"],
    domainExperience: ["FinTech", "Internal Platforms"],
    achievements: ["Improved onboarding playbook adoption across two teams", "Reduced cross-team dependency delays"],
    strengths: ["Coaching", "Planning", "Delivery governance"],
    weaknesses: ["Hands-on depth in newer frontend tooling"],
    improvementAreas: ["Delegate operational tracking to team champions"],
    managerNotes: ["Can view team analytics as a manager role in the prototype."],
    certifications: ["Certified ScrumMaster"],
    projects: [
      {
        id: "proj-003",
        name: "Platform Enablement",
        role: "Engineering Manager",
        domain: "Internal Platforms",
        duration: "Aug 2024 - Present",
        impact: "Runs enablement programs and transition readiness initiatives.",
        techStack: ["React", "Node.js", "PostgreSQL"],
        rampUp: { status: "completed", weeks: 3, notes: "Strong domain familiarity from prior platform work." },
      },
    ],
    timeline: [
      {
        id: "tl-006",
        date: "2024-08-05",
        type: "project",
        title: "Started Platform Enablement",
        description: "Moved into manager role for internal platform teams.",
      },
    ],
    visibility: { ...baseVisibility, feedbackSummary: true },
    feedbackAnalyses: [],
    goalSuggestions: [],
  },
  {
    id: "emp-003",
    name: "Kabir Singh",
    email: "kabir.singh@jtg.example",
    role: "employee",
    designation: "Senior QA Engineer",
    targetDesignation: "QA Lead",
    currentProject: "Claims Modernization",
    location: "Hyderabad",
    avatarInitials: "KS",
    skills: ["Automation", "Playwright", "API Testing", "Performance Testing"],
    domainExperience: ["Insurance", "Claims"],
    achievements: ["Built smoke automation for claims release train", "Reduced regression cycle by two days"],
    strengths: ["Automation strategy", "Release discipline"],
    weaknesses: ["Frontend implementation depth"],
    improvementAreas: ["Increase mentoring visibility"],
    managerNotes: [],
    certifications: ["ISTQB Advanced"],
    projects: [],
    timeline: [],
    visibility: { ...baseVisibility, strengths: true, achievements: true },
    feedbackAnalyses: [],
    goalSuggestions: [],
  },
];
