import type { Employee, SessionUser } from "@/types/jtg-one";

export const mockSession: SessionUser = {
  id: "emp-001",
  name: "Aarav Mehta",
  role: "employee",
};

const baseVisibility = {
  pastProjects: true,
  achievements: true,
  strengths: true,
  timeline: true,
  certifications: true,
  domainExperience: true,
  feedbackSummary: false,
  weaknesses: false,
  detailedFeedback: false,
  aiGoals: false,
  managerNotes: false,
  improvementAreas: false,
};

export const employees: Employee[] = [
  {
    id: "emp-001",
    name: "Aarav Mehta",
    email: "aarav.mehta@jtg.example",
    role: "employee",
    designation: "Software Engineer",
    targetDesignation: "Senior Software Engineer",
    currentProject: "Claims Modernization",
    location: "Bengaluru",
    avatarInitials: "AM",
    skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL"],
    domainExperience: ["Insurance", "Claims", "Internal Platforms"],
    achievements: [
      "Reduced claims dashboard load time by 38%",
      "Created onboarding notes for three new engineers",
      "Owned migration of shared form components to TypeScript",
    ],
    strengths: ["Ownership", "Frontend architecture", "Cross-team communication"],
    weaknesses: ["Deep cloud infrastructure exposure", "Advanced system design"],
    improvementAreas: ["Mentor juniors more consistently", "Document API decisions earlier"],
    managerNotes: [
      "Ready for larger module ownership if paired with a senior reviewer for design reviews.",
      "Should get more exposure to planning conversations with product and QA.",
    ],
    certifications: ["AWS Cloud Practitioner", "React Advanced Patterns Workshop"],
    projects: [
      {
        id: "proj-001",
        name: "Claims Modernization",
        role: "Frontend Engineer",
        domain: "Insurance",
        duration: "Jan 2025 - Present",
        impact: "Built reusable claim intake flows and analytics widgets.",
        techStack: ["Next.js", "TypeScript", "React Query", "Recharts"],
        rampUp: {
          status: "completed",
          weeks: 4,
          notes: "Ramp-up improved after access checklist and KT recordings were consolidated.",
        },
      },
      {
        id: "proj-002",
        name: "Agent Portal",
        role: "Full-stack Developer",
        domain: "Insurance",
        duration: "Mar 2024 - Dec 2024",
        impact: "Delivered policy search and quote comparison workflows.",
        techStack: ["React", "Express", "PostgreSQL"],
        rampUp: {
          status: "completed",
          weeks: 6,
          notes: "Initial delay caused by VPN and repository access approvals.",
        },
      },
    ],
    timeline: [
      {
        id: "tl-001",
        date: "2024-03-04",
        type: "induction",
        title: "Joined JTG induction",
        description: "Completed engineering onboarding, security training, and platform overview.",
      },
      {
        id: "tl-002",
        date: "2024-03-18",
        type: "project",
        title: "Assigned to Agent Portal",
        description: "Started as full-stack developer for policy search workflows.",
      },
      {
        id: "tl-003",
        date: "2024-05-03",
        type: "ramp-up",
        title: "Ramp-up completed",
        description: "Closed initial access gaps and shipped first independent feature.",
      },
      {
        id: "tl-004",
        date: "2025-01-13",
        type: "project",
        title: "Moved to Claims Modernization",
        description: "Transitioned to frontend ownership for claim intake experience.",
      },
      {
        id: "tl-005",
        date: "2026-04-18",
        type: "feedback",
        title: "Quarterly feedback imported",
        description: "Latest feedback highlighted ownership and frontend architecture strengths.",
      },
    ],
    visibility: baseVisibility,
    feedbackAnalyses: [],
    goalSuggestions: [
      {
        id: "goal-001",
        title: "Lead a medium-complexity module design",
        priority: "high",
        description: "Own the design proposal, API contract, risks, and rollout plan for one module.",
        timeframe: "Next 8 weeks",
        evidence: "Feedback shows high ownership but planning score trails technical execution.",
      },
    ],
  },
  {
    id: "emp-004",
    name: "Ishaan Sharma",
    email: "ishaan.sharma@jtg.example",
    role: "employee",
    designation: "Full Stack Developer",
    targetDesignation: "Senior Developer",
    currentProject: "User Management & Notifications",
    location: "Gurugram",
    avatarInitials: "IS",
    skills: ["Java", "Spring Boot", "React", "JavaScript", "Redis"],
    domainExperience: ["Product Development", "User Auth", "Payments"],
    achievements: [
      "Optimized DB queries, reducing load time by 30%",
      "Designed Notification Service architecture from scratch",
      "Maintained 85%+ code coverage with high-quality unit tests",
    ],
    strengths: ["Code Quality (SOLID)", "Requirement Clarification", "System Design"],
    weaknesses: ["Deep production deployment exposure"],
    improvementAreas: ["Mentoring outside the project", "Public technical blogging"],
    managerNotes: [
      "Excellent technical excellence and process adherence (EE).",
      "Meets expectations in delivery and timely execution (ME).",
    ],
    certifications: ["Java 17 Certified", "Spring Boot Professional"],
    projects: [
      {
        id: "proj-ishaan-1",
        name: "Notification Service",
        role: "Lead Developer",
        domain: "Product Infrastructure",
        duration: "6 Months",
        impact: "Clarified requirements and designed end-to-end notification architecture.",
        techStack: ["Java", "Spring Boot", "Redis"],
        rampUp: {
          status: "completed",
          weeks: 2,
          notes: "Ramped up quickly on Redis caching within Month 5.",
        },
      },
    ],
    timeline: [
      {
        id: "tl-is-1",
        date: "2025-11-01",
        type: "project",
        title: "Assigned to Notification Service",
        description: "Started designing architecture and clarifying end-to-end requirements.",
      },
      {
        id: "tl-is-2",
        date: "2026-03-15",
        type: "skill",
        title: "Redis Proficiency Built",
        description: "Implemented caching to optimize system performance.",
      },
      {
        id: "tl-is-3",
        date: "2026-05-20",
        type: "feedback",
        title: "Performance Review (Q2 2026)",
        description: "Exceeded expectations in Technical Excellence, Process, and Communication.",
      },
    ],
    visibility: { ...baseVisibility, feedbackSummary: true, detailedFeedback: true },
    feedbackAnalyses: [],
    goalSuggestions: [
      {
        id: "goal-is-1",
        title: "Mentor one fresher through a complete module",
        priority: "high",
        description: "Guide a new team member through requirements, design, and implementation.",
        timeframe: "Next Quarter",
        evidence: "Feedback suggests stepping up in mentoring outside the immediate project scope.",
      },
    ],
  },
  {
    id: "emp-002",
    name: "Nisha Rao",
    email: "nisha.rao@jtg.example",
    role: "manager",
    designation: "Engineering Manager",
    targetDesignation: "Senior Engineering Manager",
    currentProject: "Platform Enablement",
    location: "Pune",
    avatarInitials: "NR",
    skills: ["People Management", "Delivery", "React", "Node.js", "Architecture"],
    domainExperience: ["FinTech", "Internal Platforms"],
    achievements: ["Improved onboarding playbook adoption across two teams", "Reduced cross-team dependency delays"],
    strengths: ["Coaching", "Planning", "Delivery governance"],
    weaknesses: ["Hands-on depth in newer frontend tooling"],
    improvementAreas: ["Delegate operational tracking to team champions"],
    managerNotes: ["Can view team analytics as a manager role in the prototype."],
    certifications: ["Certified ScrumMaster"],
    projects: [
      {
        id: "proj-003",
        name: "Platform Enablement",
        role: "Engineering Manager",
        domain: "Internal Platforms",
        duration: "Aug 2024 - Present",
        impact: "Runs enablement programs and transition readiness initiatives.",
        techStack: ["React", "Node.js", "PostgreSQL"],
        rampUp: { status: "completed", weeks: 3, notes: "Strong domain familiarity from prior platform work." },
      },
    ],
    timeline: [
      {
        id: "tl-006",
        date: "2024-08-05",
        type: "project",
        title: "Started Platform Enablement",
        description: "Moved into manager role for internal platform teams.",
      },
    ],
    visibility: { ...baseVisibility, feedbackSummary: true },
    feedbackAnalyses: [],
    goalSuggestions: [],
  },
  {
    id: "emp-003",
    name: "Kabir Singh",
    email: "kabir.singh@jtg.example",
    role: "employee",
    designation: "Senior QA Engineer",
    targetDesignation: "QA Lead",
    currentProject: "Claims Modernization",
    location: "Hyderabad",
    avatarInitials: "KS",
    skills: ["Automation", "Playwright", "API Testing", "Performance Testing"],
    domainExperience: ["Insurance", "Claims"],
    achievements: ["Built smoke automation for claims release train", "Reduced regression cycle by two days"],
    strengths: ["Automation strategy", "Release discipline"],
    weaknesses: ["Frontend implementation depth"],
    improvementAreas: ["Increase mentoring visibility"],
    managerNotes: [],
    certifications: ["ISTQB Advanced"],
    projects: [],
    timeline: [],
    visibility: { ...baseVisibility, strengths: true, achievements: true },
    feedbackAnalyses: [],
    goalSuggestions: [],
  },
];
