import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { Employee } from "@/types/jtg-one";

export function GoalsSection({ employee }: { employee: Employee }) {
  return (
    <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
      <Card>
        <CardHeader>
          <CardTitle>Career direction</CardTitle>
          <CardDescription>Frontend displays suggestions generated by the backend from career ladder context.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-lg bg-slate-950 p-5 text-white">
            <p className="text-sm text-slate-300">Current designation</p>
            <p className="mt-1 text-xl font-semibold">{employee.designation}</p>
            <div className="my-5 h-px bg-white/15" />
            <p className="text-sm text-slate-300">Target designation</p>
            <p className="mt-1 text-xl font-semibold">{employee.targetDesignation}</p>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>AI-backed suggestions</CardTitle>
          <CardDescription>Mocked API response for goals, skill gaps, and next-step evidence.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {employee.goalSuggestions.map((goal) => (
            <div key={goal.id} className="rounded-lg border border-slate-200 p-4">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <h3 className="font-semibold">{goal.title}</h3>
                <Badge tone={goal.priority === "high" ? "rose" : "amber"}>{goal.priority}</Badge>
              </div>
              <p className="mt-2 text-sm leading-6 text-slate-600">{goal.description}</p>
              <p className="mt-3 text-xs font-medium text-slate-500">{goal.timeframe}</p>
              <p className="mt-2 text-xs leading-5 text-slate-500">{goal.evidence}</p>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
